project:
  type: website
  output-dir: docs

website:
  title: "Xiang Ao"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: software.qmd
        text: Software
      - href: books.qmd
        text: Online Books
      - href: blogs.qmd
        text: Blogs
      - href: other-blogs.qmd
        text: Other Blogs
    right:
      - icon: github
        href: https://github.com/xiangao

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual
